Repository mitre/menelaus, pull requests merged in 2022-07, with the labels that each got.

#62 Merge new streaming, batch ABCs and refactor KdqTree detector
  docs/source/examples/data_drift/data_drift_examples.ipynb
  examples/batch/kdqtree_batch_example.py
  examples/streaming/change_detection_example.py
  examples/streaming/concept_drift_example.py
  examples/streaming/data_drift_example.py
  src/menelaus/data_drift/__init__.py
  src/menelaus/data_drift/kdq_tree.py
  src/menelaus/drift_detector.py
  tests/menelaus/artifacts/dataCircleGSev3Sp3Train.csv
  tests/menelaus/test_drift_detector.py
  tests/menelaus/test_kdq_tree.py
Labels: enhancement

#51 Add CHANGELOG and pypi actions for release.
  .github/workflows/format.yml
  .github/workflows/pypi_push.yml
  .github/workflows/update-changelog.yaml
  CHANGELOG.md
  setup.cfg
Labels: blocked

#69 Add template for benchmarks directory
  .gitignore
  benchmarks/README.md
  benchmarks/bm_example_plot_1.py
  benchmarks/figures/bm_example_plot_1.png
  bin/Dockerfile
Labels: enhancement, benchmarking

#60 Implemented Margin Density Drift Detection (MD3) Method
  README.md
  docs/source/examples/change_detection/change_detection_examples.ipynb
  docs/source/examples/concept_drift/concept_drift_examples.ipynb
  docs/source/examples/data_drift/data_drift_examples.ipynb
  docs/source/refs.bib
  examples/change_detection_examples.py
  examples/concept_drift_examples.py
  examples/data_drift_examples.py
  src/menelaus/concept_drift/__init__.py
  src/menelaus/concept_drift/md3.py
  src/menelaus/datasets/__init__.py
  src/menelaus/datasets/make_example_data.py
  src/menelaus/datasets/rainfall_data.csv
  tests/menelaus/test_example_data.py
  tests/menelaus/test_md3.py
Labels: new detector
